### ISSUE TITLE
Stage 1 (Volleyball): Missing file tracks_normalized.pkl

### ISSUE THREAD

**Issue by daniel-richter** [JacobYuan7/DIN_GAR#3]
For executing `scripts/train_volleyball_stage1.py` there is a missing file `tracks_normalized.pkl`. To get it working, I downloaded the file available at [cvlab-epfl/social-scene-understanding](https://github.com/cvlab-epfl/social-scene-understanding/tree/master/data):

```bash
cd data/volleyball/videos
wget https://raw.githubusercontent.com/cvlab-epfl/social-scene-understanding/master/data/volleyball/tracks_normalized.pkl
```

**Comment by JacobYuan7** [comment]
Thanks for pointing out! I have merged your commits.
